update

diff --git a/playgrounds/0006/tools/manifests/dolphinscheduler/dolphinscheduler.yaml b/playgrounds/0006/tools/manifests/dolphinscheduler/dolphinscheduler.yaml
--- a/playgrounds/0006/tools/manifests/dolphinscheduler/dolphinscheduler.yaml
+++ b/playgrounds/0006/tools/manifests/dolphinscheduler/dolphinscheduler.yaml
@@ -60,16 +60,51 @@ apiVersion: v1
 kind: Secret
 metadata:
   name: release-name-postgresql
+  namespace: "default"
   labels:
     app.kubernetes.io/name: postgresql
-    helm.sh/chart: postgresql-10.3.18
+    helm.sh/chart: postgresql-12.1.15
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
-  namespace: default
 type: Opaque
 data:
-  postgresql-postgres-password: "MVdJNUE3VE1iZg=="
-  postgresql-password: "cm9vdA=="
+  postgres-password: "M3hick9oWDQ5Vg=="
+  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
+---
+# Source: dolphinscheduler-helm/charts/zookeeper/templates/scripts-configmap.yaml
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: release-name-zookeeper-scripts
+  namespace: default
+  labels:
+    app.kubernetes.io/name: zookeeper
+    helm.sh/chart: zookeeper-12.0.0
+    app.kubernetes.io/instance: release-name
+    app.kubernetes.io/managed-by: Helm
+    app.kubernetes.io/component: zookeeper
+data:
+  init-certs.sh: |-
+    #!/bin/bash
+  setup.sh: |-
+    #!/bin/bash
+
+    # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
+    # check ZOO_SERVER_ID in persistent volume via myid
+    # if not present, set based on POD hostname
+    if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
+        export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
+    else
+        HOSTNAME="$(hostname -s)"
+        if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
+            ORD=${BASH_REMATCH[2]}
+            export ZOO_SERVER_ID="$((ORD + 1 ))"
+        else
+            echo "Failed to get index from hostname $HOSTNAME"
+            exit 1
+        fi
+    fi
+    exec /entrypoint.sh /run.sh
 ---
 # Source: dolphinscheduler-helm/templates/configmap-dolphinscheduler-common.yaml
 #
@@ -236,22 +271,23 @@ spec:
     app.kubernetes.io/name: minio
     app.kubernetes.io/instance: release-name
 ---
-# Source: dolphinscheduler-helm/charts/postgresql/templates/svc-headless.yaml
+# Source: dolphinscheduler-helm/charts/postgresql/templates/primary/svc-headless.yaml
 apiVersion: v1
 kind: Service
 metadata:
-  name: release-name-postgresql-headless
+  name: release-name-postgresql-hl
+  namespace: "default"
   labels:
     app.kubernetes.io/name: postgresql
-    helm.sh/chart: postgresql-10.3.18
+    helm.sh/chart: postgresql-12.1.15
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
+    app.kubernetes.io/component: primary
     # Use this annotation in addition to the actual publishNotReadyAddresses
     # field below because the annotation will stop being respected soon but the
     # field is broken in some versions of Kubernetes:
     # https://github.com/kubernetes/kubernetes/issues/58662
     service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
-  namespace: default
 spec:
   type: ClusterIP
   clusterIP: None
@@ -266,29 +302,32 @@ spec:
   selector:
     app.kubernetes.io/name: postgresql
     app.kubernetes.io/instance: release-name
+    app.kubernetes.io/component: primary
 ---
-# Source: dolphinscheduler-helm/charts/postgresql/templates/svc.yaml
+# Source: dolphinscheduler-helm/charts/postgresql/templates/primary/svc.yaml
 apiVersion: v1
 kind: Service
 metadata:
   name: release-name-postgresql
+  namespace: "default"
   labels:
     app.kubernetes.io/name: postgresql
-    helm.sh/chart: postgresql-10.3.18
+    helm.sh/chart: postgresql-12.1.15
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
-  annotations:
-  namespace: default
+    app.kubernetes.io/component: primary
 spec:
   type: ClusterIP
+  sessionAffinity: None
   ports:
     - name: tcp-postgresql
       port: 5432
       targetPort: tcp-postgresql
+      nodePort: null
   selector:
     app.kubernetes.io/name: postgresql
     app.kubernetes.io/instance: release-name
-    role: primary
+    app.kubernetes.io/component: primary
 ---
 # Source: dolphinscheduler-helm/charts/zookeeper/templates/svc-headless.yaml
 apiVersion: v1
@@ -298,7 +337,7 @@ metadata:
   namespace: default
   labels:
     app.kubernetes.io/name: zookeeper
-    helm.sh/chart: zookeeper-6.5.3
+    helm.sh/chart: zookeeper-12.0.0
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: zookeeper
@@ -307,13 +346,10 @@ spec:
   clusterIP: None
   publishNotReadyAddresses: true
   ports:
-    
     - name: tcp-client
       port: 2181
       targetPort: client
-    
-    
-    - name: follower
+    - name: tcp-follower
       port: 2888
       targetPort: follower
     - name: tcp-election
@@ -332,20 +368,19 @@ metadata:
   namespace: default
   labels:
     app.kubernetes.io/name: zookeeper
-    helm.sh/chart: zookeeper-6.5.3
+    helm.sh/chart: zookeeper-12.0.0
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: zookeeper
 spec:
   type: ClusterIP
+  sessionAffinity: None
   ports:
-    
     - name: tcp-client
       port: 2181
       targetPort: client
-    
-    
-    - name: follower
+      nodePort: null
+    - name: tcp-follower
       port: 2888
       targetPort: follower
     - name: tcp-election
@@ -874,40 +909,41 @@ spec:
           configMap:
             name: release-name-configs
 ---
-# Source: dolphinscheduler-helm/charts/postgresql/templates/statefulset.yaml
+# Source: dolphinscheduler-helm/charts/postgresql/templates/primary/statefulset.yaml
 apiVersion: apps/v1
 kind: StatefulSet
 metadata:
   name: release-name-postgresql
+  namespace: "default"
   labels:
     app.kubernetes.io/name: postgresql
-    helm.sh/chart: postgresql-10.3.18
+    helm.sh/chart: postgresql-12.1.15
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: primary
-  annotations:
-  namespace: default
 spec:
-  serviceName: release-name-postgresql-headless
   replicas: 1
+  serviceName: release-name-postgresql-hl
   updateStrategy:
+    rollingUpdate: {}
     type: RollingUpdate
   selector:
     matchLabels:
       app.kubernetes.io/name: postgresql
       app.kubernetes.io/instance: release-name
-      role: primary
+      app.kubernetes.io/component: primary
   template:
     metadata:
       name: release-name-postgresql
       labels:
         app.kubernetes.io/name: postgresql
-        helm.sh/chart: postgresql-10.3.18
+        helm.sh/chart: postgresql-12.1.15
         app.kubernetes.io/instance: release-name
         app.kubernetes.io/managed-by: Helm
-        role: primary
         app.kubernetes.io/component: primary
-    spec:      
+    spec:
+      serviceAccountName: default
+      
       affinity:
         podAffinity:
           
@@ -925,14 +961,12 @@ spec:
           
       securityContext:
         fsGroup: 1001
+      hostNetwork: false
+      hostIPC: false
       containers:
-        - name: release-name-postgresql
-          image: docker.io/bitnami/postgresql:11.11.0-debian-10-r71
+        - name: postgresql
+          image: docker.io/bitnami/postgresql:15.2.0-debian-11-r0
           imagePullPolicy: "IfNotPresent"
-          resources:
-            requests:
-              cpu: 250m
-              memory: 256Mi
           securityContext:
             runAsUser: 1001
           env:
@@ -944,24 +978,22 @@ spec:
               value: "/bitnami/postgresql"
             - name: PGDATA
               value: "/bitnami/postgresql/data"
-            - name: POSTGRES_POSTGRES_PASSWORD
-              valueFrom:
-                secretKeyRef:
-                  name: release-name-postgresql
-                  key: postgresql-postgres-password
-            - name: POSTGRES_USER
-              value: "root"
+            # Authentication
             - name: POSTGRES_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: release-name-postgresql
-                  key: postgresql-password
-            - name: POSTGRES_DB
-              value: "dolphinscheduler"
+                  key: postgres-password
+            # Replication
+            # Initdb
+            # Standby
+            # LDAP
             - name: POSTGRESQL_ENABLE_LDAP
               value: "no"
+            # TLS
             - name: POSTGRESQL_ENABLE_TLS
               value: "no"
+            # Audit
             - name: POSTGRESQL_LOG_HOSTNAME
               value: "false"
             - name: POSTGRESQL_LOG_CONNECTIONS
@@ -970,6 +1002,7 @@ spec:
               value: "false"
             - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
               value: "off"
+            # Others
             - name: POSTGRESQL_CLIENT_MIN_MESSAGES
               value: "error"
             - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
@@ -978,40 +1011,54 @@ spec:
             - name: tcp-postgresql
               containerPort: 5432
           livenessProbe:
+            failureThreshold: 6
+            initialDelaySeconds: 30
+            periodSeconds: 10
+            successThreshold: 1
+            timeoutSeconds: 5
             exec:
               command:
                 - /bin/sh
                 - -c
-                - exec pg_isready -U "root" -d "dbname=dolphinscheduler" -h 127.0.0.1 -p 5432
-            initialDelaySeconds: 30
-            periodSeconds: 10
-            timeoutSeconds: 5
-            successThreshold: 1
-            failureThreshold: 6
+                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
           readinessProbe:
+            failureThreshold: 6
+            initialDelaySeconds: 5
+            periodSeconds: 10
+            successThreshold: 1
+            timeoutSeconds: 5
             exec:
               command:
                 - /bin/sh
                 - -c
                 - -e
+                
                 - |
-                  exec pg_isready -U "root" -d "dbname=dolphinscheduler" -h 127.0.0.1 -p 5432
+                  exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                   [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
-            initialDelaySeconds: 5
-            periodSeconds: 10
-            timeoutSeconds: 5
-            successThreshold: 1
-            failureThreshold: 6
+          resources:
+            limits: {}
+            requests:
+              cpu: 250m
+              memory: 256Mi
           volumeMounts:
             - name: dshm
               mountPath: /dev/shm
+            - name: data
+              mountPath: /bitnami/postgresql
       volumes:
         - name: dshm
           emptyDir:
             medium: Memory
-            sizeLimit: 1Gi
-        - name: data
-          emptyDir: {}
+  volumeClaimTemplates:
+    - metadata:
+        name: data
+      spec:
+        accessModes:
+          - "ReadWriteOnce"
+        resources:
+          requests:
+            storage: "8Gi"
 ---
 # Source: dolphinscheduler-helm/charts/zookeeper/templates/statefulset.yaml
 apiVersion: apps/v1
@@ -1021,36 +1068,35 @@ metadata:
   namespace: default
   labels:
     app.kubernetes.io/name: zookeeper
-    helm.sh/chart: zookeeper-6.5.3
+    helm.sh/chart: zookeeper-12.0.0
     app.kubernetes.io/instance: release-name
     app.kubernetes.io/managed-by: Helm
     app.kubernetes.io/component: zookeeper
     role: zookeeper
 spec:
-  serviceName: release-name-zookeeper-headless
   replicas: 1
   podManagementPolicy: Parallel
-  updateStrategy:
-    type: RollingUpdate
   selector:
     matchLabels:
       app.kubernetes.io/name: zookeeper
       app.kubernetes.io/instance: release-name
       app.kubernetes.io/component: zookeeper
+  serviceName: release-name-zookeeper-headless
+  updateStrategy:
+    rollingUpdate: {}
+    type: RollingUpdate
   template:
     metadata:
-      name: release-name-zookeeper
+      annotations:
       labels:
         app.kubernetes.io/name: zookeeper
-        helm.sh/chart: zookeeper-6.5.3
+        helm.sh/chart: zookeeper-12.0.0
         app.kubernetes.io/instance: release-name
         app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/component: zookeeper
     spec:
-      
       serviceAccountName: default
-      securityContext:
-        fsGroup: 1001
+      
       affinity:
         podAffinity:
           
@@ -1066,37 +1112,27 @@ spec:
               weight: 1
         nodeAffinity:
           
+      securityContext:
+        fsGroup: 1001
+      initContainers:
       containers:
         - name: zookeeper
-          image: docker.io/bitnami/zookeeper:3.6.2-debian-10-r185
+          image: docker.io/bitnami/zookeeper:3.9.0-debian-11-r0
           imagePullPolicy: "IfNotPresent"
           securityContext:
+            allowPrivilegeEscalation: false
+            runAsNonRoot: true
             runAsUser: 1001
           command:
-            - bash
-            - -ec
-            - |
-                # Execute entrypoint as usual after obtaining ZOO_SERVER_ID
-                # check ZOO_SERVER_ID in persistent volume via myid
-                # if not present, set based on POD hostname
-                if [[ -f "/bitnami/zookeeper/data/myid" ]]; then
-                  export ZOO_SERVER_ID="$(cat /bitnami/zookeeper/data/myid)"
-                else
-                  HOSTNAME=`hostname -s`
-                  if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
-                    ORD=${BASH_REMATCH[2]}
-                    export ZOO_SERVER_ID=$((ORD + 1 ))
-                  else
-                    echo "Failed to get index from hostname $HOST"
-                    exit 1
-                  fi
-                fi
-                exec /entrypoint.sh /run.sh
+            - /scripts/setup.sh
           resources:
+            limits: {}
             requests:
               cpu: 250m
               memory: 256Mi
           env:
+            - name: BITNAMI_DEBUG
+              value: "false"
             - name: ZOO_DATA_LOG_DIR
               value: ""
             - name: ZOO_PORT_NUMBER
@@ -1107,6 +1143,10 @@ spec:
               value: "10"
             - name: ZOO_SYNC_LIMIT
               value: "5"
+            - name: ZOO_PRE_ALLOC_SIZE
+              value: "65536"
+            - name: ZOO_SNAPCOUNT
+              value: "100000"
             - name: ZOO_MAX_CLIENT_CNXNS
               value: "60"
             - name: ZOO_4LW_COMMANDS_WHITELIST
@@ -1123,6 +1163,8 @@ spec:
               value: release-name-zookeeper-0.release-name-zookeeper-headless.default.svc.cluster.local:2888:3888::1 
             - name: ZOO_ENABLE_AUTH
               value: "no"
+            - name: ZOO_ENABLE_QUORUM_AUTH
+              value: "no"
             - name: ZOO_HEAP_SIZE
               value: "1024"
             - name: ZOO_LOG_LEVEL
@@ -1135,35 +1177,39 @@ spec:
                   apiVersion: v1
                   fieldPath: metadata.name
           ports:
-            
             - name: client
               containerPort: 2181
-            
-            
             - name: follower
               containerPort: 2888
             - name: election
               containerPort: 3888
           livenessProbe:
-            exec:
-              command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']
+            failureThreshold: 6
             initialDelaySeconds: 30
             periodSeconds: 10
-            timeoutSeconds: 5
             successThreshold: 1
-            failureThreshold: 6
-          readinessProbe:
+            timeoutSeconds: 5
             exec:
               command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']
+          readinessProbe:
+            failureThreshold: 6
             initialDelaySeconds: 5
             periodSeconds: 10
-            timeoutSeconds: 5
             successThreshold: 1
-            failureThreshold: 6
+            timeoutSeconds: 5
+            exec:
+              command: ['/bin/bash', '-c', 'echo "ruok" | timeout 2 nc -w 2 localhost 2181 | grep imok']
           volumeMounts:
+            - name: scripts
+              mountPath: /scripts/setup.sh
+              subPath: setup.sh
             - name: data
               mountPath: /bitnami/zookeeper
       volumes:
+        - name: scripts
+          configMap:
+            name: release-name-zookeeper-scripts
+            defaultMode: 0755
         - name: data
           emptyDir: {}
 ---
